// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETDrfrpq251TZf-r351mnPogzm56khSI',
    appId: '1:161347218661:web:f2d7979f2759f96e66780c',
    messagingSenderId: '161347218661',
    projectId: 'projectcv-42c31',
    authDomain: 'projectcv-42c31.firebaseapp.com',
    databaseURL: 'https://projectcv-42c31-default-rtdb.firebaseio.com',
    storageBucket: 'projectcv-42c31.appspot.com',
    measurementId: 'G-Z39G1ZJCQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVSXeoLW2RzCP9uQ-QkO7CS4HfWQAybx8',
    appId: '1:161347218661:android:4bdf3cc88fe77f6d66780c',
    messagingSenderId: '161347218661',
    projectId: 'projectcv-42c31',
    databaseURL: 'https://projectcv-42c31-default-rtdb.firebaseio.com',
    storageBucket: 'projectcv-42c31.appspot.com',
  );
}
